//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickLocation
    {
        public PickLocation()
        {
            this.Rentals = new HashSet<Rental>();
        }
    
        public int LocationID { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string PickAddress { get; set; }
    
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
