//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class labtask1
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
    }
}
