//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType
    {
        public CustomerType()
        {
            this.CustomerInfoes = new HashSet<CustomerInfo>();
        }
    
        public int CustTypeId { get; set; }
        public string CustTypeName { get; set; }
        public int Discount { get; set; }
    
        public virtual ICollection<CustomerInfo> CustomerInfoes { get; set; }
    }
}
