//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public System.DateTime CheckInDay { get; set; }
        public System.DateTime CheckOutDay { get; set; }
        public int CustomerId { get; set; }
        public int CarId { get; set; }
        public int DriverId { get; set; }
        public int LocationId { get; set; }
        public int RentalID { get; set; }
    
        public virtual CarInfo CarInfo { get; set; }
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual DriverInfo DriverInfo { get; set; }
        public virtual PickLocation PickLocation { get; set; }
    }
}
